require("plugins.packer")
require("plugins.cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.indentline")
require("plugins.bufferline")
require("plugins.heirline")
-- require("plugins.illuminate")
